### ISSUE TITLE
Lemp macro to remove main class and method boilerplate? 

### ISSUE THREAD

**Issue by ktodyruik** [qwertie/Loyc#20]
Hi 

I was wondering if there is a macro to eliminate main class and method boilerplate. 

Kerry

**Comment by qwertie** [comment]
There is not. I was thinking of writing a macro that would let you write global functions easily, so you'd just write something like

~~~csharp
global void Square(int x) => x*x;
~~~

and it would be translated to

~~~csharp
partial class Globals {
    // public by default, but you could specify an alternate visibility
    public static void Square(int x) => x*x;
}
~~~

Then you could write "global" functions including `global void Main(string[] args) {...}`.

The main problem is that if there are two assemblies (or even merely two namespaces) that both contain global functions, the C# compiler will pummel you mercilessly with "ambiguous!!!" errors when you refer to "Globals". And of course, you would have to manually add a `using static Globals` statement in order to call globals from classes.

**Comment by qwertie** [comment]
I guess this discussion is over?
