### ISSUE TITLE
Immutability 'with' 

### ISSUE THREAD

**Issue by ktodyruik** [qwertie/Loyc#22]
Could loyc macros implement concise immutability syntax (fsharp style) in c#? Including 'with' to make changes easily to immutable types?

**Comment by qwertie** [comment]
The grammar of C# isn't friendly to allowing people to define new operators, particularly words. For example, if we wanted to add a `with` operator, we'd run into ambiguity since `a<b> with (x: y)` is already a valid expression in C#. Also, since LeMP is a _lexical_ macro processor, macros can't make decisions based on the types involved, which may be a problem.

That said, I already solved this problem from another angle. If you use the new [ADT macro in LeMP](http://loyc.net/lemp/lemp-pattern-matching.html#algebraic-data-types), you get immutable types with free "With" functions to make changes easily.

**Comment by ktodyruik** [comment]
If there wasn't a conflict with an existing operator, could it be done? So if we used a different word other than 'with'?

**Comment by ktodyruik** [comment]
Also, would it be possible to write an immutable class macro? What I was thinking was that you can hand code immutability in C#, but it is verbose and takes effort. Generally, I was wondering how you could use macros to help with this.
